# Generated by Django 3.1.7 on 2024-12-08 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=200)),
                ('origin_nation_code', models.CharField(max_length=3)),
                ('item_type_code', models.CharField(max_length=5)),
                ('quantity_unit_code', models.CharField(max_length=5)),
                ('package_unit_code', models.CharField(max_length=5)),
                ('item_class_code', models.CharField(max_length=200)),
                ('item_tax_code', models.CharField(max_length=200)),
                ('item_opening_balance', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('item_current_balance', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('item_system_id', models.CharField(max_length=200)),
                ('item_system_name', models.CharField(max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='organization.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
