# Generated by Django 4.2.17 on 2024-12-15 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(editable=False, max_length=7, unique=True)),
                ('item_name', models.CharField(max_length=200)),
                ('origin_nation_code', models.CharField(choices=[('KE', 'Kenya'), ('US', 'United States'), ('AC', 'ASCENSION ISLAND'), ('AD', 'ANDOKRA'), ('AE', 'UNITED ARAB EMIRATES'), ('AG', 'ANTIGUA AND BARBUDA'), ('AI', 'ANGUILLA'), ('AL', 'ALBANIA'), ('AM', 'ARMENIA'), ('AN', 'NETHERLANDS ANTILLES'), ('AO', 'ANGOLA'), ('AQ', 'ANTARCTICA'), ('AR', 'ARGENTINA'), ('AS', 'AMERICAN SAMOA'), ('AT', 'AUSTRIA'), ('AU', 'AUSTRALIA'), ('AW', 'ARUBA'), ('AX', 'ALAND ISLANDS')], max_length=2)),
                ('item_type_code', models.CharField(choices=[('1', 'Raw Material'), ('2', 'Finished Product'), ('3', 'Service without stock')], max_length=2)),
                ('quantity_unit_code', models.CharField(choices=[('4B', 'Pair'), ('AV', 'Cap'), ('BA', 'Barrel'), ('BE', 'Bundle'), ('BG', 'Bag'), ('BL', 'Block'), ('BLL', 'Barrel (petroleum)'), ('BX', 'Box'), ('CA', 'Can'), ('CEL', 'Cell'), ('CMT', 'Centimetre'), ('CR', 'Carat'), ('DR', 'Drum'), ('DZ', 'Dozen'), ('GLL', 'Gallon'), ('GRM', 'Gram'), ('GRO', 'Gross'), ('KG', 'Kilogram'), ('KTM', 'Kilometre'), ('KWT', 'Kilowatt'), ('L', 'Litre'), ('LBR', 'Pound'), ('LK', 'Link'), ('LTR', 'Litre'), ('M', 'Metre'), ('M2', 'Square Metre'), ('M3', 'Cubic Metre'), ('MGM', 'Milligram'), ('MTR', 'Metre'), ('MWT', 'Megawatt hour (1000 kW.h)'), ('NO', 'Number'), ('NX', 'Part per thousand'), ('PA', 'Packet'), ('PG', 'Plate'), ('PR', 'Pair'), ('RL', 'Reel'), ('RO', 'Roll'), ('SET', 'Set'), ('ST', 'Sheet'), ('TNE', 'Tonne (metric ton)'), ('TU', 'Tube'), ('U', 'Pieces/Item'), ('YRD', 'Yard')], max_length=3)),
                ('package_unit_code', models.CharField(choices=[('AM', 'Ampoule'), ('BA', 'Barrel'), ('BC', 'Bottlecrate'), ('BE', 'Bundle'), ('BF', 'Balloon, non-protected'), ('BG', 'Bag'), ('BJ', 'Bucket'), ('BK', 'Basket'), ('BL', 'Bale'), ('BQ', 'Bottle, protected cylindrical'), ('BR', 'Bar'), ('BV', 'Bottle, bulbous'), ('BZ', 'Bag'), ('CA', 'Can'), ('CH', 'Chest'), ('CJ', 'Coffin'), ('CL', 'Coil'), ('CR', 'Wooden Box, Wooden Case'), ('CS', 'Cassette'), ('CT', 'Carton'), ('CTN', 'Container'), ('CY', 'Cylinder'), ('DR', 'Drum'), ('GT', 'Extra Countable Item'), ('HH', 'Hand Baggage'), ('IZ', 'Ingots'), ('JR', 'Jar'), ('JU', 'Jug'), ('JY', 'Jerry Can Cylindrical'), ('KZ', 'Canister'), ('LZ', 'Logs, in bundle/bunch/truss'), ('NT', 'Net'), ('OU', 'Non-Exterior Packaging Unit'), ('PD', 'Poddon'), ('PG', 'Plate'), ('PI', 'Pipe'), ('PO', 'Pilot'), ('PU', 'Traypack'), ('RL', 'Reel'), ('RO', 'Roll'), ('RZ', 'Rods, in bundle/bunch/truss'), ('SK', 'Skeletoncase'), ('TY', 'Tank, cylindrical'), ('VG', 'Bulk, gas (at 1031 mbar 15°C)'), ('VL', 'Bulk, liquid (at normal temperature/pressure)'), ('VO', 'Bulk, solid, large particles ("nodules")'), ('VQ', 'Bulk, gas (liquefied at abnormal temperature/pressure)'), ('VR', 'Bulk, solid, granular particles ("grains")'), ('VT', 'Extra Bulk Item'), ('VY', 'Bulk, fine particles ("powder")'), ('ML', 'Mills cigarette'), ('TN', 'TAN 1 TAN (Refer to 20 Bags)')], max_length=3)),
                ('item_class_code', models.CharField(choices=[('A', 'A-Exempt'), ('B', 'B-16.00%'), ('C', 'C-0%'), ('D', 'D-Non-VAT'), ('E', 'E-8%')], max_length=2)),
                ('item_tax_code', models.CharField(choices=[('A', 'Active'), ('D', 'Inactive')], max_length=1)),
                ('item_opening_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item_current_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item_system_id', models.CharField(blank=True, max_length=200, null=True)),
                ('item_system_name', models.CharField(blank=True, max_length=200, null=True)),
                ('itemCd', models.CharField(max_length=16, unique=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='organization.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
