services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"       # RabbitMQ broker
      - "15672:15672"     # RabbitMQ Management UI

  celery:
    build: .
    command: celery -A your_project_name worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
