services:

  celery:
    restart: always
    build:
      context: .
    command: celery -A etimsx worker -l info
    volumes:
      - ./:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - etimsx
      - rabbitmq3

  # RabbitMQ - queue
  rabbitmq3:
    restart: always
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: mysecurepassword

  # Celery Beat (New Service)
  celery-beat:
    restart: always
    build:
      context: .
    command: celery -A etimsx beat --loglevel=info
    volumes:
      - ./:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - etimsx
      - celery
      - rabbitmq3
      

  etimsx:
    container_name: etimsx
    restart: always
    build:
      context: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8001:8000
    env_file:
      - .env