# Generated by Django 3.1.7 on 2024-12-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_name', models.CharField(blank=True, max_length=50)),
                ('organization_pin', models.CharField(blank=True, max_length=50)),
                ('organization_email', models.EmailField(blank=True, max_length=50)),
                ('organization_physical_address', models.CharField(blank=True, max_length=100)),
                ('organization_phone', models.CharField(blank=True, max_length=15)),
                ('organization_key', models.CharField(editable=False, max_length=7, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
