# Generated by Django 4.2.17 on 2024-12-15 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(editable=False, max_length=7, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_pin', models.CharField(max_length=200, unique=True)),
                ('customer_address', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=200, unique=True)),
                ('customer_email', models.EmailField(max_length=200, unique=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='organization.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
