# Generated by Django 4.2.17 on 2025-01-25 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_pin',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
    ]
