# Generated by Django 4.2.17 on 2025-03-04 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_code', models.CharField(max_length=20, unique=True)),
                ('declaration_date', models.DateField()),
                ('declaration_number', models.CharField(max_length=50)),
                ('hs_code', models.CharField(max_length=20)),
                ('item_name', models.CharField(max_length=255)),
                ('import_status_code', models.CharField(max_length=5)),
                ('origin_country', models.CharField(max_length=5)),
                ('export_country', models.CharField(max_length=5)),
                ('package_count', models.PositiveIntegerField()),
                ('package_unit_code', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_unit_code', models.CharField(max_length=10)),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier_name', models.CharField(max_length=255)),
                ('agent_name', models.CharField(max_length=255)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice_currency', models.CharField(max_length=5)),
                ('invoice_exchange_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('verified', models.BooleanField(default=False)),
                ('payload', models.JSONField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='organization.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
