# Generated by Django 4.2.17 on 2024-12-15 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(editable=False, max_length=7, unique=True)),
                ('trader_invoice_number', models.CharField(max_length=200)),
                ('receipt_number', models.BigIntegerField()),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('credit_note', 'Credit Note'), ('receipt', 'Receipt')], max_length=50)),
                ('document_path', models.FileField(blank=True, null=True, upload_to='transaction_documents/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organization.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
