# Generated by Django 4.2.17 on 2025-01-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reason',
            field=models.CharField(blank=True, default='sale', max_length=200, null=True),
        ),
    ]
