# Generated by Django 4.2.17 on 2025-01-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='original_receipt_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
