# Generated by Django 4.2.17 on 2025-01-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transaction_original_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receipt_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
