# Generated by Django 4.2.17 on 2025-01-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_movement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmovement',
            name='movement_reason',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
