# Generated by Django 4.2.17 on 2025-01-11 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transaction_original_receipt_number'),
        ('api_tracker', '0002_apirequestlog_customer_apirequestlog_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apirequestlog',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='apirequestlog',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction'),
        ),
    ]
