# Generated by Django 4.2.17 on 2025-01-20 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
        ('api_tracker', '0003_remove_apirequestlog_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequestlog',
            name='Purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.purchase'),
        ),
    ]
