# Generated by Django 4.2.17 on 2025-01-20 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_tracker', '0004_apirequestlog_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apirequestlog',
            old_name='Purchase',
            new_name='purchase',
        ),
    ]
