# Generated by Django 4.2.17 on 2025-01-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tin', models.CharField(max_length=15, unique=True)),
                ('branch_id', models.CharField(max_length=5)),
                ('device_serial_number', models.CharField(max_length=50, unique=True)),
                ('initialized', models.BooleanField(default=False)),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('control_unit_id', models.CharField(blank=True, max_length=50, null=True)),
                ('internal_key', models.CharField(blank=True, max_length=255, null=True)),
                ('sign_key', models.CharField(blank=True, max_length=255, null=True)),
                ('communication_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
