# Generated by Django 4.2.17 on 2025-03-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_remove_device_device_id_device_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_serial_number',
            field=models.CharField(max_length=50),
        ),
    ]
