# Generated by Django 4.2.17 on 2025-03-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_device_device_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='tin',
            field=models.CharField(max_length=15),
        ),
    ]
