# Generated by Django 4.2.17 on 2024-12-15 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(editable=False, max_length=7, unique=True)),
                ('movement_type', models.CharField(choices=[('ADD', 'Addition'), ('REMOVE', 'Removal'), ('TRANSFER', 'Transfer')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventories', to='item.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
