# Generated by Django 4.2.17 on 2025-01-02 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
        ('sales_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitems',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales_items', to='transaction.transaction'),
        ),
    ]
