# Generated by Django 5.1.4 on 2024-12-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_items', '0002_salesitems_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitems',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
